### ISSUE TITLE
Overriden ScopedRefs being disposed on hot reload causing error

### ISSUE THREAD

**Issue by PaulHalliday** [jinyus/lite_ref#24]
Thanks for the library! I've been having fun using it on a couple projects.

I'm running into an issue that's relatively hard to reproduce.

**Overview**

I'm currently using the latest version, 0.7.0, as verified per `pubspec.lock`/inspection.

I'm displaying a widget that has live data from a local websocket server. When there is no data coming from the server (or via a toggle), I'm showing demo data.

For example:

```
final fakeDataProvider = Ref.scoped((ctx) => FakeDataProvider());
final real = Ref.scoped((ctx) => RealClassImpl());
final fake = Ref.scoped((ctx) {
  return FakeClassImpl(fakeDataProvider(ctx));
});

liveData.value
      ? const Widget()
      : LiteRefScope(overrides: {
          real.overrideWith((ctx) => fake(ctx))
        }, 
        child: const Widget()),
),
```

`Widget` accesses data from `real` and overriding it with `fake` (using the same interface) feeds data to the signals via a `Timer`. Both `real` and `fake` extend from `Disposable` and appropriately dispose their data on unmount.

**Issue**

Hot reloading calls the `dispose` on my `fake` data instance, _but_ does not start my timer again _and in most scenarios_ `signals` ends up throwing a `Unable to watch {signal} after it has already been disposed` error and:

```
Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4743:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4757:6)
#2      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4792:12)
#3      LiteRefScope._of (package:lite_ref/src/scoped/scope_widget.dart:36:17)
#4      ScopedRef.of (package:lite_ref/src/scoped/ref.dart:92:34)
#5      ScopedRef.call (package:lite_ref/src/scoped/ref.dart:135:35)
```

I'm also getting a `Cannot modify an unmodifiable set` error when this occurs):
```
The following UnsupportedError was thrown while finalizing the widget tree:
Unsupported operation: Cannot change an unmodifiable set

When the exception was thrown, this was the stack:
#0      _UnmodifiableSetMixin._throwUnmodifiable (dart:collection/set.dart:355:5)
set.dart:355
#1      _UnmodifiableSetMixin.clear (dart:collection/set.dart:362:19)
set.dart:362
#2      _RefScopeElement.unmount (package:lite_ref/src/scoped/scope_widget.dart:153:22)
scope_widget.dart:153

//
  @override
  void unmount() {
    for (final ref in _cache.values) {
      ref._dispose();
    }
    _cache.clear();
    
    scope.overrides?.clear();
    _autoDisposeBindings.clear();
    _parent = null;
    super.unmount();
  }
```

(The `overrides` set in my widget tree is entirely static, not computed/changing).

This essentially seems that, upon hot reload/save/xyz, it's depending on the previous scoped reference.

**Things I've tried**

* I've tried abstracting the core premise of this into a standalone project, but finding it difficult to reproduce.
* If I use Riverpod to essentially create the same functionality, i.e using `ProviderScope` and subsequent `Provider.autoDispose`/`ref.onDispose`s instead, I don't run into this issue. 

I appreciate that this issue is of little use as I'm unable to provide an actual reproduction case, so I expect this to be closed -- but I thought I'd log this anyway in-case I'm doing something wrong.

This could also be related to: https://github.com/jinyus/lite_ref/issues/22

**Comment by zupat** [comment]
I am trying to reproduce the issue...does this look like what you're doing?

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:state_beacon/state_beacon.dart';

const k100ms = Duration(milliseconds: 100);

class DataProvider implements Disposable {
  DataProvider([int multiplier = 1]) {
    timer = Timer.periodic(k100ms * 10, (timer) {
      controller.add(timer.tick * multiplier);
    });
  }

  Timer? timer;
  final controller = StreamController<int>();

  Stream<int> numbers() => controller.stream;

  @override
  void dispose() {
    timer?.cancel();
    controller.close();
  }
}

class Repository with BeaconController {
  Repository(this.provider);

  final DataProvider provider;

  late final numbers = B.streamRaw(provider.numbers, initialValue: 0); //
  late final doubledNumbers = B.derived(() => numbers.value * 2);
}

final dataProviderRef = Ref.scoped((ctx) => DataProvider());
final realRef = Ref.scoped((ctx) => Repository(dataProviderRef.read(ctx)));
final fakeRef = Ref.scoped((ctx) => Repository(DataProvider(10)));

final showReal = Beacon.writable(false);
void main() {
  runApp(const LiteRefScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: const Center(child: HomePage()),
        floatingActionButton: IconButton.filled(
          onPressed: showReal.toggle,
          icon: const Icon(Icons.repeat),
          iconSize: 32,
        ),
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return showReal.watch(context)
        ? const TextDisplay()
        : LiteRefScope(
            overrides: {
              realRef.overrideWith(((ctx) => fakeRef.read(ctx))),
            },
            child: const TextDisplay(),
          );
  }
}

class TextDisplay extends StatelessWidget {
  const TextDisplay({super.key});

  @override
  Widget build(BuildContext context) {
    final repo = realRef.of(context);
    final value = repo.doubledNumbers.watch(context);
    return Text('$value');
  }
}
```

**Comment by PaulHalliday** [comment]
Apologies for the delayed reply!

Yup -- effectively this.

EDIT: [I can reproduce it here](https://github.com/PaulHalliday/lite_test). I'm using a key above the widget in this example to trigger the issue, but I'm not directly doing this in my actual implementation.

**Comment by zupat** [comment]
I figured out the bug, trying to work out a solution. This is the minimal reproduction:

```dart
import 'package:flutter/material.dart';
import 'package:lite_ref/lite_ref.dart';

class Increment implements Disposable {
  Increment() {
    print('Creating Increment $hashCode');
  }
  int by = 1;

  @override
  void dispose() {
    print('Disposed Increment $hashCode');
  }
}

class Counter implements Disposable {
  Counter(this.increment) {
    print('Creating Counter $hashCode with ${increment.hashCode}');
  }
  int count = 0;

  final Increment increment;

  @override
  void dispose() {
    print('Disposed Counter $hashCode');
  }
}

final incrementRef = Ref.scoped((ctx) => Increment());
final counterRef = Ref.scoped<Counter>((ctx) => throw UnimplementedError());

void main() {
  runApp(const LiteRefScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          /// UniqueKey is used to force rebuild on save
          key: UniqueKey(),
          child: SizedBox(
            width: 300,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                LiteRefScope(
                  overrides: {
                    counterRef
                        .overrideWith((ctx) => Counter(incrementRef.read(ctx))),
                  },
                  child: Builder(
                    builder: (context) {
                      final count = counterRef.of(context).count;
                      return Text('Counter: $count');
                    },
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by zupat** [comment]
Fixed in this PR: https://github.com/jinyus/lite_ref/pull/27

I submitted a PR to your test repo with the fix. lmk if all is good: https://github.com/PaulHalliday/lite_test/pull/1

**Comment by PaulHalliday** [comment]
Thanks for your work on this!

I've updated my main project to 0.8.0 and confirmed this via lock/inspection/flutter clean/etc.

Here's my results:

1. The lite_test minimal is fixed and works fine. Hot reload doesn't trigger the issue anymore.
2. In my _actual_ project, the issue remains. The specific implementation of the widget isn't far from the original `lite_test` (with a different child being passed per selected demo).
3. The timer is restarted correctly for this selection of the widget tree. In the prior version, in order for it to restart, I had to rebuild from a higher tree (i.e. select a different demo widget and then re-select this one, master/detail within the same page).

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following UnsupportedError was thrown while finalizing the widget tree:
Unsupported operation: Cannot change an unmodifiable set

When the exception was thrown, this was the stack:
#0      _UnmodifiableSetMixin._throwUnmodifiable (dart:collection/set.dart:355:5)
set.dart:355
#1      _UnmodifiableSetMixin.clear (dart:collection/set.dart:362:19)
set.dart:362
#2      _RefScopeElement.unmount (package:lite_ref/src/scoped/scope_widget.dart:179:22)
scope_widget.dart:179
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2077:13)
framework.dart:2077
#4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#5      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6755:14)
framework.dart:6755
#6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#8      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6755:14)
framework.dart:6755
#9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
framework.dart:5539
#12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
framework.dart:5539
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#17     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
framework.dart:5539
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
framework.dart:5539
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
framework.dart:5539
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
framework.dart:5539
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
framework.dart:5539
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6755:14)
framework.dart:6755
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
framework.dart:5539
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
framework.dart:5539
#39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
framework.dart:5539
#42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
framework.dart:5539
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
framework.dart:5539
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#50     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6755:14)
framework.dart:6755
#51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#52     ListIterable.forEach (dart:_internal/iterable.dart:49:13)
iterable.dart:49
#53     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2086:25)
framework.dart:2086
#54     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2765:15)
framework.dart:2765
#55     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3175:7)
framework.dart:3175
#56     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1143:19)
binding.dart:1143
#57     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
binding.dart:443
#58     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
binding.dart:1392
#59     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
binding.dart:1313
#60     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
binding.dart:1171
#61     _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#62     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
platform_dispatcher.dart:419
#63     _drawFrame (dart:ui/hooks.dart:283:31)
hooks.dart:28

/// Then this triggers read warnings from my Signals that are still attempting to be read:

flutter: signal warning: [87] has been read after disposed: #0      Signal.value (package:signals_core/src/core/signal.dart:299:97)
#1      FakeDataProvider.startTimer.<anonymous closure> 
#2      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#3      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by zupat** [comment]
Please try this version and report back.

```yaml
lite_ref:
        git:
            url: https://github.com/jinyus/lite_ref.git
            path: packages/lite_ref
            ref: 195e0e8581c9365a0746eed45da73bd68694bbb2
```

**Comment by PaulHalliday** [comment]
I think that's it! 

I can no longer reproduce this issue in my project.

Thanks for your hard work on this, I appreciate it.

**Comment by zupat** [comment]
Nice, I published the fix in v0.8.1

**Comment by PaulHalliday** [comment]
I seem to be getting this one again.

The widget tree is essentially the same as our original usecase, just with a Signals `Watch` over a `CustomPaint` that passes specific configuration data into the widget. 

Upon changing the configuration data in another part of the tree (within the same context), I get:

```
The following assertion was thrown building Watch<CustomPaint>(dirty, dependencies: [LiteRefScope], state: _WatchState<CustomPaint>#5d698):
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4743:9)
framework.dart:4743
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4757:6)
framework.dart:4757
#2      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4792:12)
framework.dart:4792
#3      LiteRefScope._of (package:lite_ref/src/scoped/scope_widget.dart:36:17)
scope_widget.dart:36
#4      ScopedRef.of (package:lite_ref/src/scoped/scoped_ref.dart:85:34)
scoped_ref.dart:85
#5      ScopedRef.call (package:lite_ref/src/scoped/scoped_ref.dart:128:35)
scoped_ref.dart:128
#8      _WatchState.build.<anonymous closure> (package:signals_flutter/src/watch/widget.dart:217:33)
widget.dart:217
#9      Effect._callback (package:signals_core/src/core/effect.dart:350:32)
effect.dart:350
#10     new Effect (package:signals_core/src/core/effect.dart:328:7)
effect.dart:328
#11     effect (package:signals_core/src/core/effect.dart:591:20)
effect.dart:591
#12     _WatchState.build (package:signals_flutter/src/watch/widget.dart:214:12)
widget.dart:214
#13     StatefulElement.build (package:flutter/src/widgets/framework.dart:5599:27)
```

I'm able to fix this if I add a `UniqueKey()` to my `LiteRefScope` to force a recreation here. Hot reload does not kick the timer away/re-render the widget.

**Comment by zupat** [comment]
I think this means that the context being used has been unmounted. Are you calling it in a method by chance?

**Comment by PaulHalliday** [comment]
I was originally accessing the fake data provider within Ref.scope directly, i.e. `fakeDataProvider(context)`,  but for the above example I tried to access it by passing context into the class momentarily to see if it made a difference.   

If I use it the original way I was doing it (accessing it directly within Ref.scope and passing the result to the model on return), I get:  

```
flutter: computed warning: [116|signal_] has been read after disposed: #0      Computed.value (package:signals_core/src/core/computed.dart:512:97)
#1      MyWidget.build.<anonymous closure>.<anonymous closure> 
#2      _WatchState.rebuild (package:signals_flutter/src/watch/widget.dart:196:34)
#3      _WatchState.didUpdateWidget (package:signals_flutter/src/watch/widget.dart:209:30)
#4      StatefulElement.update (package:flutter/src/widgets/framework.dart:5659:55)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#8      ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#10     Element.updateChildren (package:flutter/src/widgets/framework.dart:3976:32)
#11     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6929:17)
```

This doesn’t happen every time, and the majority of the time there are no errors/debug logs.

If I swap `lite_ref` for `Riverpod` with the following changes:  

```dart
final real = Ref.scoped<Model>(
  (ctx) => ModelImpl(),
);

final realRiverpod = Provider.autoDispose<Model>((ref) {
  return ModelImpl();
});

final fake = Ref.scoped<Model>((ctx) {
  return FakeModel(fakeDataProvider(ctx));
});

final fakeRiverpod = Provider.autoDispose<Model>((ref) {
  return FakeModel(ref.watch(fakeOverlayDataProviderRiverpod));
});

final fakeOverlayDataProvider = Ref.scoped<FakeOverlayDataProvider>((ctx) {
  final model = FakeOverlayDataProvider();
  model.startTimer();
  
  return model;
});

final fakeOverlayDataProviderRiverpod = Provider.autoDispose<FakeOverlayDataProvider>((ref) {
  final model = FakeOverlayDataProvider();
  model.startTimer();

  ref.onDispose(() {
    model.dispose();
  });

  return model;
});
```

With the usage of:

```dart
ProviderScope(
  overrides: [
    realRiverpod.overrideWith((ref) => ref.watch(fakeRiverpod)),
  ],
  child: child,
)
```

vs

```dart
LiteRefScope(
  overrides: {
    real.overrideWith((ctx) => fake(ctx)),
  },
  child: child,
),
```

Everything then works fine. I can change the configuration and the widget updates without the need for a unique key (timer continues and doesn't cause an entire recreation of the widget).

_[I realise the implementation of ProviderScope/LiteRefScope/etc are unrelated -- just adding my findings regarding overriding inside of my production widget tree in this example.]_

**Comment by zupat** [comment]
Is `MyWidget` using the Ref? That error could only occur if the widget is accessing a signal of a Controller that has been disposed. 

Could you use `mysignal.watch(context)` instead of `Watch` to see if the problem persist?

**Comment by PaulHalliday** [comment]
Ah -- that seems to have fixed it.

Apologies! I had assumed `Watch` and `.watch(context)` were interchangeable here.

**Comment by zupat** [comment]
They're supposed to be, but there are a few quirks with `Watch`.
